kind: pipeline
name: default
  
steps:
  - name: config-set-up 
    # image: gargikekre/positional_strategy_005:2
    # auth:
    #   username: gargikekre  
    #   password: P@ssw0rd2459945
    # when:
    #   status:
    #     - failure
    #     - success
    # commands:
    #   - cat config.py
      # - sed "s|item1|'${ITEM}'|g" config.py
      # - sed "s|market_key1|'${MARKET_KEY}'|g" config.py
      # - sed "s|market_secret1|'${MARKET_SECRET}'|g" config.py
      # - sed "s|order_key1|'${ORDER_KEY}'|g" config.py
      # - sed "s|order_secret1|'${ORDER_SECRET}'|g" config.py

  # - name: build-docker
  #   commands:
  #     - pip install -r requirements.txt
      # - python3 main_bnf_buy.py 
      # - python3 main_bnf_sell.py
      


