kind: pipeline
name: default
  
steps:
  - name: config-set-up 
    image: python
              # auth:
              #   username: gargikekre  
              #   password: P@ssw0rd2459945
    when:
      status:
        - failure
        - success
    commands:
      - touch confi.py
      - sed "s|item1|'${ITEM}'|g" confi.py
      - sed "s|market_key1|'${MARKET_KEY}'|g" confi.py
      - sed "s|market_secret1|'${MARKET_SECRET}'|g" confi.py
      - sed "s|order_key1|'${ORDER_KEY}'|g" confi.py
      - sed "s|order_secret1|'${ORDER_SECRET}'|g" confi.py
      - pip install -r requirements.txt
      - python3 src/main_bnf_buy.py 
      - python3 src/main_bnf_sell.py
      


